name: coa_progress_tracking_app
description: A new Flutter project.
# The following line prevents the package from being accidentally published to
# pub.dev using `flutter pub publish`. This is preferred for private packages.
publish_to: 'none' # Remove this line if you wish to publish to pub.dev

# The following defines the version and build number for your application.
# A version number is three numbers separated by dots, like 1.2.43
# followed by an optional build number separated by a +.
# Both the version and the builder number may be overridden in flutter
# build by specifying --build-name and --build-number, respectively.
# In Android, build-name is used as versionName while build-number used as versionCode.
# Read more about Android versioning at https://developer.android.com/studio/publish/versioning
# In iOS, build-name is used as CFBundleShortVersionString while build-number is used as CFBundleVersion.
# Read more about iOS versioning at
# https://developer.apple.com/library/archive/documentation/General/Reference/InfoPlistKeyReference/Articles/CoreFoundationKeys.html
# In Windows, build-name is used as the major, minor, and patch parts
# of the product and file versions while build-number is used as the build suffix.
version: 1.0.0+1

environment:
  sdk: '>=3.1.4 <4.0.0'
  flutter: ^3.1.4

# Dependencies specify other packages that your package needs in order to work.
# To automatically upgrade your package dependencies to the latest versions
# consider running `flutter pub upgrade --major-versions`. Alternatively,
# dependencies can be manually updated by changing the version numbers below to
# the latest version available on pub.dev. To see which dependencies have newer
# versions available, run `flutter pub outdated`.
dependencies:
  flutter:
    sdk: flutter


  # The following adds the Cupertino Icons font to your application.
  # Use with the CupertinoIcons class for iOS style icons.
  cupertino_icons: ^1.0.2
  #firebase_core: ^2.21.0
  flutter_heatmap_calendar: ^1.0.5
  geolocator: ^10.1.0
  #cloud_firestore: ^4.12.2
  #firebase_auth: ^4.12.1
  flutter_clean_calendar: ^1.1.0
  intl: ^0.17.0
  audioplayers: ^5.2.0
  flutter_slidable: ^3.0.1
  volume_control: ^0.1.5
  perfect_volume_control: ^1.0.5
  flutter_tts: ^3.8.3
  supabase_flutter: ^2.0.0
  email_validator: ^2.1.16
  mutex: ^3.1.0
  nock: ^1.2.3

dev_dependencies:
  flutter_test:
    sdk: flutter

  # The "flutter_lints" package below contains a set of recommended lints to
  # encourage good coding practices. The lint set provided by the package is
  # activated in the `analysis_options.yaml` file located at the root of your
  # package. See that file for information about deactivating specific lint
  # rules and activating additional ones.
  flutter_lints: ^2.0.0

# For information on the generic Dart part of this file, see the
# following page: https://dart.dev/tools/pub/pubspec

# The following section is specific to Flutter packages.
flutter:

  # The following line ensures that the Material Icons font is
  # included with your application, so that you can use the icons in
  # the material Icons class.
  uses-material-design: true

  # To add assets to your application, add an assets section, like this:
  assets:
    - assets/COA-Orange-Background.webp
    - assets/
    - assets/coa-logo.JPG
    - assets/balloon_red.png
    - assets/burger.png
    - assets/bodyparts/foot.png
    - assets/bodyparts/stomach.png
    - assets/bodyparts/arms.png
    - assets/bodyparts/legs.png
    - assets/bodyparts/chin.png
    - assets/bodyparts/nose.png

    # MARK - CUSTOM VOICES:
    # Female voices for custom audio.
      # Credit: Morgan Cruz
    - assets/voices/female/Progress.mp3
    - assets/voices/female/a_little_bit.mp3
    - assets/voices/female/alright.mp3
    - assets/voices/female/angry.mp3
    - assets/voices/female/arms.mp3
    - assets/voices/female/back.mp3
    - assets/voices/female/bad.mp3
    - assets/voices/female/body_parts.mp3
    - assets/voices/female/caprisun.mp3
    - assets/voices/female/celebrations.mp3
    - assets/voices/female/cheeks.mp3
    - assets/voices/female/chest.mp3
    - assets/voices/female/chin.mp3
    - assets/voices/female/confetti_.mp3
    - assets/voices/female/curious.mp3
    - assets/voices/female/drink.mp3
    - assets/voices/female/ears.mp3
    - assets/voices/female/elbows.mp3
    - assets/voices/female/emergency.mp3
    - assets/voices/female/emotions.mp3
    - assets/voices/female/excellent.mp3
    - assets/voices/female/eyes.mp3
    - assets/voices/female/feet.mp3
    - assets/voices/female/fine.mp3
    - assets/voices/female/food.mp3
    - assets/voices/female/food___drink.mp3
    - assets/voices/female/games.mp3
    - assets/voices/female/good.mp3
    - assets/voices/female/hair.mp3
    - assets/voices/female/hands.mp3
    - assets/voices/female/happy.mp3
    - assets/voices/female/head.mp3
    - assets/voices/female/headache.mp3
    - assets/voices/female/help.mp3
    - assets/voices/female/hip.mp3
    - assets/voices/female/horrible.mp3
    - assets/voices/female/hurts.mp3
    - assets/voices/female/i_am_in_pain.mp3
    - assets/voices/female/i_am_uncomforatable.mp3
    - assets/voices/female/i_need_to_go_potty.mp3
    - assets/voices/female/i_need_to_go_to_the_bathroom.mp3
    - assets/voices/female/is_uncomforable.mp3
    - assets/voices/female/juice.mp3
    - assets/voices/female/knee.mp3
    - assets/voices/female/left.mp3
    - assets/voices/female/left_arm.mp3
    - assets/voices/female/left_ear.mp3
    - assets/voices/female/left_elbow.mp3
    - assets/voices/female/left_eye.mp3
    - assets/voices/female/left_foot.mp3
    - assets/voices/female/left_hand.mp3
    - assets/voices/female/left_leg.mp3
    - assets/voices/female/left_shoulder.mp3
    - assets/voices/female/left_side.mp3
    - assets/voices/female/legs.mp3
    - assets/voices/female/milestones.mp3
    - assets/voices/female/mouth.mp3
    - assets/voices/female/my.mp3
    - assets/voices/female/neck.mp3
    - assets/voices/female/no.mp3
    - assets/voices/female/normal.mp3
    - assets/voices/female/nose.mp3
    - assets/voices/female/o.mp3
    - assets/voices/female/one.mp3
    - assets/voices/female/overwhelmed.mp3
    - assets/voices/female/player_o_wins_.mp3
    - assets/voices/female/player_x_wins_.mp3
    - assets/voices/female/playground.mp3
    - assets/voices/female/please.mp3
    - assets/voices/female/potty.mp3
    - assets/voices/female/reset_board.mp3
    - assets/voices/female/right.mp3
    - assets/voices/female/right_arm.mp3
    - assets/voices/female/right_ear.mp3
    - assets/voices/female/right_elbow.mp3
    - assets/voices/female/right_eye.mp3
    - assets/voices/female/right_foot.mp3
    - assets/voices/female/right_hand.mp3
    - assets/voices/female/right_leg.mp3
    - assets/voices/female/right_shoulder.mp3
    - assets/voices/female/right_side.mp3
    - assets/voices/female/sad.mp3
    - assets/voices/female/select_a_body_part.mp3
    - assets/voices/female/settings.mp3
    - assets/voices/female/shoulders.mp3
    - assets/voices/female/speech.mp3
    - assets/voices/female/stomach.mp3
    - assets/voices/female/teeth.mp3
    - assets/voices/female/thank_you.mp3
    - assets/voices/female/three.mp3
    - assets/voices/female/tic_tac_toe.mp3
    - assets/voices/female/tongue.mp3
    - assets/voices/female/two.mp3
    - assets/voices/female/water.mp3
    - assets/voices/female/x.mp3
    - assets/voices/female/yes.mp3

    # Male voices for custom audio.
    - assets/voices/male/drink.aif
    - assets/voices/male/food.aif
    - assets/voices/male/food___drink.aif
  #   - images/a_dot_burr.jpeg
  #   - images/a_dot_ham.jpeg

  # An image asset can refer to one or more resolution-specific "variants", see
  # https://flutter.dev/assets-and-images/#resolution-aware

  # For details regarding adding assets from package dependencies, see
  # https://flutter.dev/assets-and-images/#from-packages

  # To add custom fonts to your application, add a fonts section here,
  # in this "flutter" section. Each entry in this list should have a
  # "family" key with the font family name, and a "fonts" key with a
  # list giving the asset and other descriptors for the font. For
  # example:
  fonts:
    - family: Inter
      fonts:
        - asset: fonts/Inter-Regular.ttf
        - asset: fonts/Inter-Bold.ttf
          weight: 700
  
  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
  #
  # For details regarding fonts from package dependencies,
  # see https://flutter.dev/custom-fonts/#from-packages
